In [14]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [15]:
import pandas as pd

from rockyclickup.wrapper import Session
from rockyclickup.models import FSA
from rockyclickup.utils import response_to_dataframe

In [16]:
clickup = Session()

In [17]:
all_fsas = clickup.get_full_list(model=FSA)

fsa_df = response_to_dataframe(all_fsas)

Field not in config.db: client 3195a6c7-9403-4aee-81ed-c9dec04557c4

In [18]:
for col in ['date_plan_start', 'date_plan_end']:
    fsa_df[col] = pd.to_datetime(fsa_df[col])

In [30]:
fsa_df['client_id'] = fsa_df['client_fsa'].apply(lambda x: x[0] if (isinstance(x, list) and len(x) > 0) else None)

In [40]:
lpf_map = {}

for client_id, client_df in fsa_df.groupby("client_id"):

    sorted_df = client_df.sort_values("date_plan_start")

    oldest_lpf_value = bool(sorted_df.iloc[0].get("lpf"))

    lpf_map[client_id] = oldest_lpf_value

In [ ]:
fsa_df['is_lpf'] = fsa_df['client_id'].map(lpf_map)
fsa_df['is_lpf'].fillna(False, inplace=True)

plans_to_correct = fsa_df[
    (fsa_df['is_lpf'] != fsa_df['lpf']) &
    (fsa_df['client_id'].notna())
]

plans_to_correct[["id", 'client_id', "name", "lpf", "is_lpf"]]

C:\Users\james.richmond\AppData\Local\Temp\ipykernel_30268\2234167395.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fsa_df['is_lpf'].fillna(False, inplace=True)
C:\Users\james.richmond\AppData\Local\Temp\ipykernel_30268\2234167395.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  fsa_df['is_lpf'].fillna(False, inplace=True)

             id  client_id             name    lpf  is_lpf
2338  86879krc7  86877zmvu  RMRHRT FSA 2024   True   False
1061  86899teph  86877zk8w  RMRCQA FSA 2024   True   False
1131  8688v4xu3  86877zkp7  RMRCRU FSA 2024   True   False
1018  8689kp3zn  86877zjmy  RMRBIS FSA 2024   True   False
1179  8688azqgt  86877zm57   RMREL FSA 2024   True   False
...         ...        ...              ...    ...     ...
35    868fradrq  86877zjpf  RMRBLM FSA 2025  False    True
31    868frae1z  86877zjwj  RMRCHE FSA 2025  False    True
8     868fraf1a  868ar9ke8  RMRMGA FSA 2025  False    True
22    868fraed4  86877zkpc  RMRCFG FSA 2025  False    True
1016  8689kwb74  86877zqtp  RMRNXC FSA 2025  False    True

[340 rows x 5 columns]

In [ ]:
fsa_df = fsa_df.sort_values("date_plan_start")
fsa_df[fsa_df['date_plan_start'].isna()]

             id custom_id  ...  date_plan_end run_out_end_formula
49    868f9cp99      None  ...            NaT                None
83    868e8bd3p      None  ...            NaT                None
176   868duvjre      None  ...            NaT                None
205   868den0gt      None  ...            NaT                None
937   868b3h54w      None  ...            NaT                None
...         ...       ...  ...            ...                 ...
1338  8687u1pc6      None  ...            NaT                None
1339  8687u1pc1      None  ...            NaT                None
1340  8687txj5b      None  ...            NaT                None
1351  8687fxau2      None  ...            NaT                None
1354  8687b3crp      None  ...            NaT                None

[121 rows x 81 columns]