In [1]:
%load_ext autoreload
%autoreload 2

In [2]:

import json
import pandas as pd
import datetime as dt
from dateutil.relativedelta import relativedelta

from rockyelevate.wrapper import Session as ELV
from rockyelevate.utils import response_to_dataframe as elv_res_2_df

from rockyclickup.wrapper import Session as RCU
from rockyclickup.utils import response_to_dataframe as rcu_res_2_df, datetime_nearest_day, convert_datetime
from rockyclickup.database_interface import get_all_fields
from rockyclickup.models import (
    Client,
    FSA,
    DCA,
    HSA,
    HRA,
    ADO,
    LSA,
    EDU,
    PKG,
    TRN,
    MODEL_LOOKUP
)

In [3]:
elv = ELV("PROD", multithread=True, max_threads=40)
rcu = RCU()

In [4]:
ELV_ACCOUNT_TYPE_MAP = {
    "HCFSA": "FSA",
    "DCAP": "DCA",
    "HSA": "HSA",
    "HRA": "HRA",
    "TRANSIT": "TRN",
    "PARKING": "PKG",
    "LIFESTYLE": "LSA"
}

LIST_ID_MAP = {
    v.category: k
    for k, v
    in MODEL_LOOKUP.items()
}

In [5]:
# collect all Elevate Organizations

try:
    with open("all_orgs_res.json", 'r') as f:
        all_orgs_res = json.load(f)
        
    all_orgs_df = elv_res_2_df(all_orgs_res)
    print(f"{len(all_orgs_df)} organizations found in file")

except FileNotFoundError:
    all_orgs_res = elv.get_organizations(
        types=["SYSTEM", "PARTNER", "DISTRIBUTOR", "COMPANY", "SUBSIDIARY", "SUBGROUP"],
        statuses=["PENDING", "ACTIVE", "TERMINATED", "ACTIVATION_FAILED"],
        # details=['PARTNER_EXTERNAL_IDENTIFER']
    )
    all_orgs_df = elv_res_2_df(all_orgs_res)
    
    with open("all_orgs_res.json", "w") as f:
        json.dump(all_orgs_res, f, indent=4)

    print(f"{len(all_orgs_res)} organizations found from Elevate API")

1123 organizations found in file

In [6]:
# collect all Elevate plans

try:
    with open("all_plans_res.json", "r") as f:
        all_plans_res = json.load(f)
        
    all_plans_df = elv_res_2_df(all_plans_res)
    print(f"{len(all_plans_df)} plans found in file")

except FileNotFoundError:
    all_oids = [o.get("id") for o in all_orgs_res]
    all_plans_res = elv.get_plans_by_org(oids=all_oids, detail=True)
    all_plans_df = elv_res_2_df(all_plans_res)

    with open("all_plans_res.json", "w") as f:
        json.dump(all_plans_res, f, indent=4)

    print(f"{all_plans_res} plans found from Elevate API")

6926 plans found in file

In [7]:
# collect all ClickUp Clients

try:
    with open("all_clients_res.json", "r") as f:
        all_clients_res = json.load(f)
        
    all_clients_df = rcu_res_2_df(all_clients_res)
    print(f"{len(all_clients_df)} clients found in file")

except FileNotFoundError: 
    all_clients_res = rcu.get_full_list(model=Client)
    all_clients_df = rcu_res_2_df(all_clients_res)

    with open("all_clients_res.json", "w") as f:
        json.dump(all_clients_res, f, indent=4)

    print(f"{len(all_clients_df)} clients found from ClickUp API")

Field not in config.db: update_account_managers 702d85f6-7155-447c-9019-206db17ab27c
Field not in config.db: ducks 80f59460-7b7d-4652-9d9c-f1029b146ede
Field not in config.db: data_transmission_details 2bd919bf-6695-4f13-9f80-9e7b077bc83c
Field not in config.db: divisional_invoicing 951e9aa5-c6d9-4ad1-98a9-118b5d478640
Field not in config.db: temp_am_cobra f1c08a6f-3a1c-4392-8967-bbcd9501e1a8
Field not in config.db: temp_account_manager 159d31bb-e617-4d3a-b900-021cc0ad4542
Field not in config.db: data_start 7d44c3ea-fbe2-42d7-a21a-0e8f42bd8f1b
Field not in config.db: temp_flex_divisions 0d2211c9-b8c9-417e-b020-74ca30273509
Field not in config.db: temp_cobra_divisions e1798c36-372a-446b-8612-de839429d43c
Field not in config.db: data_end 3b8c9ecd-1e23-442a-8155-2b15c1559dee
2797 clients found in file

In [8]:
# collect all ClickUp Plans

try:
    with open("all_clickup_plans_res.json", "r") as f:
        all_plan_responses = json.load(f)

    print(f"{len(all_plan_responses)} clickup plans found in file")

except FileNotFoundError:
    all_plan_responses = []

    for plan_model in [FSA, DCA, HSA, HRA, ADO, LSA, EDU, PKG, TRN]:
        list_response = rcu.get_full_list(model=plan_model)
        all_plan_responses.extend(list_response)

    with open("all_clickup_plans_res.json", "w") as f:
        json.dump(all_plan_responses, f, indent=4)

    print(f"{len(all_plan_responses)} plans fetched from ClickUp API")
    
clickup_plan_df = rcu_res_2_df(all_plan_responses)

6253 clickup plans found in file
Field not in config.db: structure 5515a85d-d6fb-45bf-8e40-081e41b5e11b

In [9]:
# add ClickUp Client details to ClickUp Plan rows

client_merge_df = all_clients_df.copy()
cu_plan_merge_df = clickup_plan_df.copy()

relation_fields = [
    'client_fsa',
    'client_hsa',
    'client_dca',
    'client_hra',
    'client_lsa',
    'client_pkg',
    'client_ado',
    'client_edu',
    'client_trn'
]


# replace empty NaNs with empty lists
for col in relation_fields:
    cu_plan_merge_df[col] = cu_plan_merge_df[col].apply(
        lambda x: x if isinstance(x, list) else []
    )

# combine all client ids from relation fields into single column
cu_plan_merge_df['client_id_list'] = cu_plan_merge_df.apply(
    lambda row: list(set(sum([row[field] for field in relation_fields], []))),
    axis=1
)

# check if there are any plans that have more than one client linked
more_than_one = cu_plan_merge_df[cu_plan_merge_df['client_id_list'].apply(lambda x: len(x) > 1)]
if not more_than_one.empty:
    print(f"{len(more_than_one)} plans have more than one client linked!!!")

# extract first id from the list of client ids (these lists should always have either 1 or 0 items)
cu_plan_merge_df["client_id"] = cu_plan_merge_df['client_id_list'].apply(
    lambda x: x[0] if len(x) > 0 else None
)

# rename columns that appear in both dataframes
matching_columns = [c for c in client_merge_df.columns if c in cu_plan_merge_df.columns]
client_rename_map = { c: f"client_{c}" for c in matching_columns }
plan_rename_map = { c: f"plan_{c}" for c in matching_columns }

client_merge_df = client_merge_df.rename(columns={"id": "client_id"})
client_merge_df = client_merge_df.rename(columns=client_rename_map)
cu_plan_merge_df = cu_plan_merge_df.rename(columns=plan_rename_map)

# finally merge them
client_plan_df = pd.merge(left=cu_plan_merge_df, right=client_merge_df, on="client_id", how='left')

# fix clickup dates

for col in ["date_plan_start", "date_plan_end"]:
    client_plan_df[col] = pd.to_datetime(client_plan_df[col])
    client_plan_df[col] = client_plan_df[col].apply(lambda x: datetime_nearest_day(x))

In [10]:
# add Elevate Organization details onto Elevate Plan rows

all_orgs_df = all_orgs_df.rename(columns={
    "id": "organization_id",
    "parent_id": "organization_parent_id"
})

all_plans_df = all_plans_df.rename(columns={
    "parent_id": "plan_parent_id"
})

org_plan_df = pd.merge(left=all_plans_df, right=all_orgs_df, on='organization_id', how='left')

In [11]:
# filter elevate plan df to rows that start ~january 1st 2026

for col in ['plan_year.valid_from', 'plan_year.valid_to']:
    org_plan_df[col] = pd.to_datetime(org_plan_df[col])

january_df = org_plan_df[
    (org_plan_df['plan_year.valid_from'] >= dt.datetime(2025, 12, 31)) &
    (org_plan_df['plan_year.valid_from'] <= dt.datetime(2026, 1, 2))
]

print(f"{len(january_df)} 01/01/2026 plans")
display(january_df['plan_year.valid_from'].value_counts())

# normalize account_type
january_df['normalized_account_type'] = january_df['account_type.account_type'].apply(lambda x: ELV_ACCOUNT_TYPE_MAP.get(x, x))

2019 01/01/2026 plans

plan_year.valid_from
2026-01-01    2019
Name: count, dtype: int64

C:\Users\james.richmond\AppData\Local\Temp\ipykernel_6712\3060842955.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  january_df['normalized_account_type'] = january_df['account_type.account_type'].apply(lambda x: ELV_ACCOUNT_TYPE_MAP.get(x, x))

In [12]:
# check what elevate plans have already been created clickup

rolled_plan_map = {}

for _, row in january_df.iterrows():
    clickup_plan_search = client_plan_df[
        (client_plan_df["date_plan_start"] == row['plan_year.valid_from']) &
        (client_plan_df["date_plan_end"] == row['plan_year.valid_to']) &
        (client_plan_df["rmr_code"] == row['external_identifier']) &
        (client_plan_df["plan_list.name"] == row['normalized_account_type'])
    ]

    if not clickup_plan_search.empty:
        rolled_plan_map[row['id']] = clickup_plan_search['plan_id'].to_list()

if all([len(x) == 1 for  x in rolled_plan_map.values()]):
    rolled_plan_map = {k: v[0] for k, v in rolled_plan_map.items()}

print(f"{len(rolled_plan_map)} elevate plans have already been created on clickup")

48 elevate plans have already been created on clickup

In [13]:
# try to find last years clickup plan card for each row

previous_plan_card_map = {}

for _, row in january_df.iterrows():
    if pd.isna(row['plan_year.valid_from']) or pd.isna(row['plan_year.valid_to']):
        continue
    
    clickup_plan_search = client_plan_df[
        (
            (client_plan_df["date_plan_start"] == row['plan_year.valid_from'] - relativedelta(years=1)) |
            (client_plan_df["date_plan_end"] == row['plan_year.valid_to'] - relativedelta(years=1)) |
            (
                (client_plan_df["date_plan_start"] <= row['plan_year.valid_from'] - relativedelta(years=1) + relativedelta(days=1)) &
                (client_plan_df["date_plan_start"] >= row['plan_year.valid_from'] - relativedelta(years=1) - relativedelta(days=1))
            )
        ) &
        (client_plan_df["rmr_code"] == row['external_identifier']) &
        (client_plan_df["plan_list.name"] == row['normalized_account_type'])
    ]

    if not clickup_plan_search.empty:
        previous_plan_card_map[row['id']] = clickup_plan_search['plan_id'].to_list()

In [14]:
for elv_plan_id, previous_cu_plans in previous_plan_card_map.items():
    if len(previous_cu_plans) > 1:
        print(f"{elv_plan_id}: {previous_cu_plans}")

93261: ['868c5gaxj', '868c5gawx']
93260: ['868c5gaxj', '868c5gawx']
96046: ['868c5gutu', '868c5gun4']
96047: ['868c5gutu', '868c5gun4']
96555: ['868c5fdyy', '868c5fdxz']
96562: ['868c5fdyy', '868c5fdxz']
93235: ['868c5g30g', '868c5g2zf']
93238: ['868c5g30g', '868c5g2zf']
95231: ['868c5g4gh', '868c5g4fh']
95233: ['868c5g4gh', '868c5g4fh']
95234: ['868c5g4gh', '868c5g4fh']
97164: ['868c6q5nd', '868c492a5']
97176: ['868c5ez7w', '8688t8h80']
97177: ['868c5ez66', '8688t8h7a']
97305: ['868bgm0jn', '868b91bw8']
97309: ['868bgm0jn', '868b91bw8']

In [15]:
client_rmrcode_map = { r['rmr_code']: r['id'] for _, r in all_clients_df.iterrows() }
id_lookup_df = all_orgs_df.copy()[['organization_id', 'external_identifier']]
id_lookup_df['client_id'] = all_orgs_df['external_identifier'].apply(lambda x: client_rmrcode_map.get(x))

In [16]:
print(len(id_lookup_df[id_lookup_df['organization_id'].isna()]))
print(len(id_lookup_df[id_lookup_df['external_identifier'].isna()]))
print(len(id_lookup_df[id_lookup_df['client_id'].isna()]))

org_to_client_map = { r['organization_id']: r['client_id'] for _, r in id_lookup_df.iterrows() }

0
0
7

In [17]:
january_df['client_id'] = january_df['organization_id'].apply(lambda x: org_to_client_map.get(x))

C:\Users\james.richmond\AppData\Local\Temp\ipykernel_6712\1659501238.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  january_df['client_id'] = january_df['organization_id'].apply(lambda x: org_to_client_map.get(x))

In [18]:
[c for c in client_plan_df.columns if "list" in c]

['plan_checklists',
 'plan_list.id',
 'plan_list.name',
 'plan_list.access',
 'client_id_list',
 'client_checklists',
 'client_list.id',
 'client_list.name',
 'client_list.access']

In [19]:
# filter out hsa plans for clients that already have an hsa card
orgs_w_hsa = client_plan_df[client_plan_df['plan_list.name'] == "HSA"]['rmr_code'].unique()
print(len(orgs_w_hsa))

no_dup_hsa = january_df[
    ~(
        (january_df['external_identifier'].isin(orgs_w_hsa)) &
        (january_df['account_type.account_type'] == "HSA")
    )
]

print(len(no_dup_hsa))

672
1508

In [20]:
# narrow january df to columns needed to create plan cards

narrow_df = no_dup_hsa.copy()

narrow_df = narrow_df[[
    "id",
    "client_id",
    "plan_code",
    "normalized_account_type",
    "plan_status",
    "organization_id",
    "external_identifier",
    "plan_year.valid_from",
    "plan_year.valid_to",
    "plan_primary_config.is_carded.is_carded",
    "plan_primary_config.max_election_amount_type.max_election_amount_type",
    "plan_primary_config.max_election_amount_type.max_election_amount",
    # "annual_election_auto_adjust",
    "plan_primary_config.min_election_amount_type.min_election_amount",
    "plan_coverage_config.run_out_type.run_out_days_amount",
    "plan_coverage_config.claims_deadline_end_of_coverage_type.claims_deadline_end_of_coverage_days_amount",
    "plan_coverage_config.claims_deadline_end_of_coverage_type.claims_deadline_end_of_coverage_type",
    "plan_coverage_config.grace_period_type.grace_period_days_amount",
    "plan_account_funding_config.is_rollover.is_rollover",
    "plan_account_funding_config.max_rollover_amount.max_rollover_amount",
    "plan_account_funding_config.min_rollover_amount.min_rollover_amount",
    # "plan_account_funding_config.is_auto_enrollment.is_auto_enrollment"
]].rename(columns={
    "id": "elv_id",
    "external_identifier": "rmrcode",
    "plan_code": "elv_plan_code",
    "plan_year.valid_from": "date_plan_start",
    "plan_year.valid_to": "date_plan_end",
    "plan_primary_config.is_carded.is_carded": "card",
    "plan_primary_config.max_election_amount_type.max_election_amount": "annual_election_max",
    "plan_primary_config.min_election_amount_type.min_election_amount": "annual_election_min",
    "plan_coverage_config.run_out_type.run_out_days_amount": "run_out",
    "plan_coverage_config.claims_deadline_end_of_coverage_type.claims_deadline_end_of_coverage_days_amount": "run_out_termed_ee",
    "plan_coverage_config.claims_deadline_end_of_coverage_type.claims_deadline_end_of_coverage_type": "run_out_termed_ee_matches_plan",
    "plan_coverage_config.grace_period_type.grace_period_days_amount": "grace_period",
    "plan_account_funding_config.is_rollover.is_rollover": "rollover",
    "plan_account_funding_config.max_rollover_amount.max_rollover_amount": "rollover_max",
    "plan_account_funding_config.min_rollover_amount.min_rollover_amount": "rollover_min"
})

In [21]:
# format fields for clickup

def get_card_name(row):
    new_name = f"{row['rmrcode']} {row['normalized_account_type']}"

    if row['normalized_account_type'] != "HSA":
        new_name = f"{new_name} {row['date_plan_start'].year}"

narrow_df["name"] = narrow_df.apply(lambda row: f"{row['rmrcode']} {row['normalized_account_type']} {row['date_plan_start'].year}", axis=1)

def get_lpf(row):
    if row['normalized_account_type'] != "FSA":
        return None
    
    if row['elv_id'] not in previous_plan_card_map:
        return False
    
    plan_ids = previous_plan_card_map.get(row['elv_id'])
    if not plan_ids or len(plan_ids) == 0:
        return False
    
    plan_id = plan_ids[0]

    matching_plans = client_plan_df[client_plan_df['plan_id'] == plan_id]

    if not matching_plans.empty:
        return matching_plans.iloc[0]["lpf"]

    return False
narrow_df['lpf'] = narrow_df.apply(get_lpf, axis=1)

def get_account_manager(row):
    # get account manager from previous plan card
    if row['elv_id'] in previous_plan_card_map:
        plan_id = previous_plan_card_map.get(row['elv_id'])[0]
        matching_plans = client_plan_df[client_plan_df['plan_id'] == plan_id]
        return matching_plans.iloc[0]['plan_account_manager']
    
    # if no previous plan card, get account manager from client
    matching_client = all_clients_df[all_clients_df['rmr_code'] == row['rmrcode']]
    if not matching_client.empty:
        return matching_client.iloc[0]['account_manager']
    
    return None

narrow_df['account_manager'] = narrow_df.apply(get_account_manager, axis=1)

def get_admin_start(row):
    # get date admin start from previous plan card
    if row['elv_id'] in previous_plan_card_map:
        plan_id = previous_plan_card_map.get(row['elv_id'])[0]
        matching_plans = client_plan_df[client_plan_df['plan_id'] == plan_id]
        return matching_plans.iloc[0]['plan_date_admin_start']
    
    # if no preivous plan card, get date plan start from client
    matching_client = all_clients_df[all_clients_df['rmr_code'] == row['rmrcode']]
    if not matching_client.empty:
        return matching_client.iloc[0]['date_admin_start']
    
    return None
narrow_df['date_admin_start'] = narrow_df.apply(get_admin_start, axis=1)

def get_auto_post(row):
    # get auto_post_contributions from previous plan card
    if row['elv_id'] in previous_plan_card_map:
        plan_id = previous_plan_card_map.get(row['elv_id'])[0]
        matching_plans = client_plan_df[client_plan_df['plan_id'] == plan_id]
        return matching_plans.iloc[0]['auto_post_contributions']
    
    return None
narrow_df['auto_post_contributions'] = narrow_df.apply(get_auto_post, axis=1)

# def get_rollover_eligibility(row):
#     if row["plan_account_funding_config.is_auto_enrollment.is_auto_enrollment"] == True:
#         return "Must enroll in following year to receive rollover"
#     else:
#         return None
# narrow_df['rollover_elligibility'] = narrow_df.apply(get_rollover_eligibility, axis=1)


narrow_df['annual_election_auto_adjust'] = narrow_df['plan_primary_config.max_election_amount_type.max_election_amount_type'].apply(lambda x: True if x == "IRS_LIMIT" else False)
narrow_df['annual_election_max'] = narrow_df.apply(
    lambda row:
        0.0 if row['plan_primary_config.max_election_amount_type.max_election_amount_type'] == "UNLIMITED"
        else row['annual_election_max'],
    axis=1
)

narrow_df['run_out_termed_ee_matches_plan'] = narrow_df['run_out_termed_ee_matches_plan'].apply(lambda x: x == "PRE_DEFINED_END_DATE")

narrow_df['list_id'] = narrow_df['normalized_account_type'].apply(lambda x: LIST_ID_MAP.get(x.lower()))


# add client_id to all relation fields
plan_types = [m.category for m in MODEL_LOOKUP.values()]
for plan_type in plan_types:
    narrow_df[f"client_{plan_type}"] = narrow_df['client_id']

In [107]:

all_db_fields = get_all_fields()

field_map = {
    f.custom_name: f
    for f in all_db_fields
}


def format_dict(plan_dict: dict):
    new_dict = {}
    print(f"{plan_dict['elv_id']} {plan_dict['account_manager']}")
    for key, value in plan_dict.items():
    
        if (isinstance(value, list) and len(value) == 0) or (not isinstance(value, list) and pd.isna(value)):
            continue

        if key == "list_id":
            new_dict[key] = int(value)
            continue

        if key not in field_map:
            new_dict[key] = value
            continue

        field_type = field_map.get(key).type

        match field_type:
            case "list_relationship":
                if isinstance(value, list):
                    new_dict[key] = value
                else:
                    new_dict[key] = [value]

            case "users":
                if isinstance(value, list):
                    new_dict[key] = value
                else:
                    new_dict[key] = [value]

            case "short_text":
                new_dict[key] = str(value)

            case "number":
                new_dict[key] = int(value)

            case "currency":
                new_dict[key] = float(value)

            case "checkbox": 
                new_dict[key] = bool(value)

            case "date":
                new_dict[key] = convert_datetime(value, correct_tz_offset=True)

            case _:
                print(field_type)
                    
    return new_dict     


formatted_dicts = [
    format_dict(r.to_dict()) for _, r in narrow_df.iterrows()
]
# plan_dicts = [
#     r.to_dict() for _, r in narrow_df.iterrows()
# ]


# for plan_dict in plan_dicts:
#     new_dict = format_dict(plan_dict)

95260 [90071342]
95285 [75432760]
95258 [75432781]
95251 [90071342]
95256 [90071243]
95277 [75432760]
95257 [90071243]
95259 [90071243]
95293 [81535121]
95309 [75432760]
95307 [75432760]
95286 [81535121]
95305 [75432760]
95322 [75432760]
95292 [75432760]
95319 [75432753]
95289 [75432760]
95314 [75432753]
95250 [75432781]
93245 [75432768]
93246 [75432768]
93613 [75432768]
95308 [90071243]
95313 [90071243]
95311 [90071243]
94793 [75432760]
95265 [75432760]
95264 [75432760]
95267 [75432760]
95280 [75432760]
95325 [75432768]
95324 [75432768]
95301 [90071243]
95310 [90071243]
95304 [90071243]
95316 [90071243]
95270 [75432768]
95266 [75432768]
95290 [75432760]
95295 [75432760]
95288 [75432781]
95279 [75432781]
95294 [75432781]
95297 [75432781]
95273 [75432760]
95278 [75432760]
95282 [90071243]
95291 [90071243]
95284 [90071243]
95287 [90071243]
95269 [75432781]
95272 [75432781]
95767 [75432768]
95766 [75432768]
95296 [75432768]
95299 [75432768]
95326 []
95328 []
95327 [75432768]
95329 [75432768]
95337 [75432768]
95342 [75432768]
95333 [75432727]
95338 [75432727]
95334 [81535121]
95335 [81535121]
95345 [81535121]
95341 [81535121]
95344 [75432760]
95361 [75432727]
95348 [75432760]
95354 [75432727]
95357 [81535121]
95360 [81535121]
95377 [81524762, 81592842]
95343 [90071342]
95380 [81524762, 81592842]
95347 [90071342]
95346 [75432727]
95372 [90071243]
95366 [90071243]
93261 [75432768]
93260 [75432768]
95356 [75432753]
95350 [75432753]
95370 [90071342]
95375 [90071342]
97138 [81392438]
95388 [75432768]
95391 [75432768]
95371 [75432768]
95368 [75432768]
95367 [75432727]
95364 [75432727]
95392 [81592842]
95359 [75432753]
95365 [75432753]
95379 [90071342]
95383 [90071342]
95378 [90071342]
95385 [90071342]
95406 [75432760]
95412 [75432760]
95394 [90071243]
95387 [90071243]
95393 [75432768]
95369 [90071243]
95362 [90071243]
95408 [75432741]
95403 [75432741]
95401 [75432768]
95399 [75432768]
95405 [75432727]
95402 [75432727]
95413 [75432753]
95415 [75432753]
95409 [75432727]
95410 [75432727]
95404 [75432710]
95416 [75432710]
95419 [75432753]
95423 [75432753]
95425 [75432781]
95418 [75432781]
95435 [75432768]
95438 [75432768]
95430 [75432753]
95434 [75432753]
95440 [81392438]
95446 [81392438]
95442 [81392438]
95426 [81535121]
95470 [75432760]
95427 [75432760]
95429 [75432760]
95447 [81392438]
95445 [81392438]
95439 [75432753]
95436 [75432753]
95448 [75432768]
95450 [75432768]
95444 [75432781]
95443 [75432781]
95459 [81535121]
95453 [81535121]
95467 [81524762, 81592842]
95469 [81524762, 81592842]
93662 [75432768]
95465 [75432760]
95466 [75432760]
95462 [75432760]
95461 [75432768]
95464 [75432768]
95472 [75432768]
95477 [75432768]
97465 [90071342]
97466 [90071342]
95486 [75432753]
95488 [75432753]
95460 [87313870]
95468 [87313870]
95471 [87313870]
95474 [87313870]
95491 [75432741]
95484 [75432741]
95487 [75432727]
95494 [75432727]
95496 [75432768]
95499 [75432768]
95505 [75432727]
95500 [75432727]
95482 [75432781]
95476 [81535121]
95479 [81535121]
95503 [75432768]
95498 [75432768]
95501 [75432768]
95495 [75432741]
95502 [75432741]
95510 [81535121]
95515 [81535121]
95518 [75432741]
95524 [75432741]
95517 [81392438]
95521 [81392438]
95523 [75432760]
95527 [75432760]
95507 [75432760]
95514 [75432760]
95516 [75432760]
95519 [75432760]
95520 [81535121]
95528 [75432768]
95530 [75432768]
95529 [81535121]
95531 [81535121]
95548 [81592842]
95549 [81592842]
95541 [90071243]
95534 [90071243]
95536 [90071243]
95547 [75432768]
95545 [75432768]
95526 [75432727]
95533 [75432727]
95543 [75432727]
95551 [75432760]
95550 [75432760]
95535 [81535121]
95554 [90071243]
95556 [90071243]
95555 [75432760]
95553 [75432760]
95564 [75432741]
95566 [75432741]
95568 [75432741]
95570 [75432741]
95561 [75432727]
95565 [75432727]
95569 [81392438]
95573 [81392438]
95571 [75432768]
95576 [75432768]
94175 [81524762, 81592842]
94174 [81524762, 81592842]
95578 [75432760]
95579 [75432760]
95577 [90071243]
95580 [90071243]
95586 [90071243]
95592 [90071243]
95583 [75432760]
95584 [75432760]
95596 [75432768]
95590 [75432768]
95598 [75432753]
95604 [75432753]
94481 [75432753]
94482 [75432753]
95588 [75432781]
95589 [75432781]
95591 [75432727]
95593 [75432727]
95599 [75432727]
95597 [75432727]
95624 [87313870]
95625 [87313870]
95601 [75432760]
95602 [75432760]
95618 [75432768]
95617 [75432768]
95619 [75432768]
95605 [75432727]
95608 [75432727]
95615 [81524762, 81592842]
95610 [81524762, 81592842]
90295 [75432768]
95636 [75432760]
95611 [75432781]
95606 [75432781]
95638 [75432760]
93267 [75432768]
93270 [75432768]
93627 [75432768]
95643 [90071243]
95642 [90071243]
95626 [75432753]
95628 [75432753]
95632 [75432781]
95630 [75432781]
95631 [81535121]
95629 [81535121]
95616 [75432753]
95614 [75432753]
95639 [81535121]
95641 [81535121]
95646 [75432760]
95644 [75432760]
97193 [75432781]
95649 [75432768]
95651 [75432768]
95654 [75432781]
95657 [75432781]
95652 [75432768]
95653 [75432768]
95664 [75432768]
95663 [75432768]
95658 [75432727]
95659 [75432727]
95678 [90071243]
95679 [90071243]
95666 [81392438]
95667 [81392438]
95675 [75432781]
95674 [75432781]
95660 [75432753]
95661 [75432753]
95713 [90071342]
95712 [90071342]
95669 [75432760]
95671 [75432760]
95670 [75432760]
95673 [75432760]
95684 [81535121]
95685 [81535121]
95686 [81535121]
95689 [81535121]
95701 [75432768]
95703 [75432768]
95681 [75432741]
95683 [75432741]
95682 [75432741]
95699 [81592842]
95698 [81592842]
95700 [81592842]
95702 [81592842]
95690 [81592842]
95693 [81592842]
95694 [75432753]
95695 [75432753]
95710 [75432760]
95709 [75432760]
94194 [75432760]
95697 [75432727]
94195 [75432760]
95696 [75432727]
95725 [75432760]
95723 [75432760]
95707 [81535121]
95705 [81535121]
94199 [75432760]
94201 [75432760]
94198 [75432760]
95734 [75432753]
95735 [75432753]
95716 [75432727]
95718 [75432727]
95728 [81535121]
95730 [81535121]
95714 [75432760]
95717 [75432760]
95721 [81592842]
95724 [81592842]
95736 [75432741]
95737 [75432741]
95739 [75432768]
95738 [75432768]
95742 [75432760]
95745 [75432760]
95759 [81524762, 81592842]
95752 [81392438]
95753 [81392438]
95746 [75432760]
95744 [75432760]
95749 [75432760]
95748 [75432760]
95779 [81392438]
95781 [81392438]
90657 [90071243]
90655 [90071243]
95764 [90071243]
95762 [90071243]
95756 [75432768]
95758 [75432768]
95775 [75432768]
95776 [75432768]
93635 [75432768]
93637 [75432768]
93634 [75432768]
95772 [75432768]
95773 [75432768]
95761 [75432760]
95763 [75432760]
95786 [75432781]
95790 [75432781]
95794 [75432781]
95797 [75432781]
95784 [75432753]
95777 [75432753]
95778 [75432753]
95780 [75432753]
95770 [81592842]
95792 [75432753]
95783 [75432753]
95800 [75432753]
95795 [87313870]
95799 [75432760]
95802 [75432760]
95789 [90071243]
95791 [90071243]
95788 [81392438]
95793 [81392438]
95808 []
95807 [75432760]
95804 [75432768]
95809 [75432768]
95812 []
95815 []
95816 [75432768]
95817 [75432768]
95819 [75432760]
95820 [75432760]
95823 [75432727]
95824 [75432727]
95829 []
95831 []
95838 [87313870]
95836 [87313870]
95832 [75432781]
95835 [75432781]
95839 [81392438]
95840 [81392438]
95844 [75432768]
95847 [75432768]
95846 [87313870]
95851 [87313870]
95842 [75432781]
95843 [75432781]
95855 [75432781]
95852 [75432781]
95858 [75432781]
95854 [75432753]
95856 [75432753]
95860 [81535121]
95862 [81535121]
95864 [75432760]
95861 [75432760]
95869 [87313870]
95870 [87313870]
95863 [75432760]
95865 [75432760]
95874 [75432727]
95872 [75432741]
95873 [75432741]
95876 [75432727]
95871 [75432760]
95875 [75432760]
95890 [75432760]
95887 [75432760]
95880 [87313870]
95881 [75432741]
95882 [75432741]
95896 [75432768]
95892 [75432768]
95884 [75432768]
95886 [75432768]
95889 [75432741]
95893 [75432741]
95891 [75432741]
95895 [75432781]
95898 [75432781]
95901 [75432781]
95899 [75432760]
95905 [75432760]
95883 [75432727]
95885 [75432727]
95906 [75432753]
95904 [75432753]
95907 [75432753]
95915 [75432753]
95902 [90071243]
95903 [90071243]
95909 [75432768]
95912 [75432768]
94188 []
94189 []
94191 []
95911 [90071243]
95914 [90071243]
95917 [90071243]
95919 [90071243]
95932 [75432768]
95933 [75432768]
95913 [75432727]
95916 [75432727]
95926 [75432768]
95923 [75432768]
95922 [81524762, 81592842]
95931 [81524762, 81592842]
95935 [75432760]
95936 [75432760]
95934 [75432760]
95930 [75432760]
95939 [90071243]
95944 [90071243]
95924 [81392438]
95927 [81392438]
95949 [90071342]
95960 [90071342]
95941 [75432760]
95946 [75432760]
95940 [75432741]
95942 [75432741]
95947 [75432768]
95945 [75432768]
95951 [75432727]
95954 [81592842]
95956 [81592842]
95959 [81592842]
95950 [90071342]
95952 [90071342]
95967 [75432753]
95971 [75432753]
95958 [75432760]
95972 [75432753]
95970 [75432781]
95974 [75432781]
95981 [75432727]
95977 [75432727]
95963 [75432768]
95962 [75432768]
95983 [81592842]
95985 [81592842]
95991 [81592842]
95988 [81592842]
95966 [75432727]
95976 [75432727]
95978 [90071243]
95980 [90071243]
95979 [81535121]
95982 [81535121]
95975 [75432781]
95968 [75432781]
96000 [75432768]
95993 [75432768]
96006 [75432768]
95989 [75432760]
95996 [75432760]
95999 [75432760]
96002 [75432760]
95995 [75432781]
95997 [75432781]
96003 [75432710, 81535121]
96007 [75432710, 81535121]
93257 [75432768]
93258 [75432768]
93616 [75432768]
96005 [75432760]
96008 [75432760]
96015 [75432760]
96014 [75432760]
96010 [75432727]
96009 [75432727]
96020 [75432760]
96021 [75432760]
96042 [90071243]
96046 [90071243]
96043 [90071243]
96047 [90071243]
96039 [75432760]
96045 [75432760]
96024 [81592842]
96025 [81592842]
96022 [75432781]
96023 [75432781]
96028 [81535121]
96030 [81535121]
96027 [81535121]
96032 [81535121]
96031 [75432760]
96029 [75432760]
96016 [75432768]
96018 [75432768]
96033 [75432781]
96035 [75432781]
96050 [75432753]
96048 [75432753]
96038 [81392438]
96036 [81392438]
96060 [75432753]
96064 [75432753]
96063 [75432753]
96061 [75432753]
96054 [75432760]
96051 [75432760]
96055 [75432760]
96057 [75432760]
96053 [75432760]
94192 [75432760]
96069 [81535121]
96071 [81535121]
96065 [75432753]
96067 [75432753]
96076 [81535121]
96077 [81535121]
96080 [75432760]
96082 [75432760]
94549 [81592842]
94548 [81592842]
94551 [81592842]
94550 [81592842]
96066 [75432760]
96068 [75432760]
96073 [75432760]
93263 [75432768]
93265 [75432768]
96074 [90071243]
96078 [90071243]
96081 [75432753]
96083 [75432753]
96088 [75432753]
96087 [75432753]
96086 [75432768]
96085 [75432768]
96093 [75432753]
96090 [75432753]
96095 [75432753]
96091 [75432753]
96096 [90071243]
96100 []
96103 [81524762, 81592842]
96104 [81524762, 81592842]
96094 [75432781]
96099 [75432781]
96092 [75432781]
96107 [90071243]
96111 [90071243]
96102 [75432727]
96101 [75432727]
96106 [75432753]
96109 [75432760]
96112 [75432760]
96116 [75432760]
96114 [75432753]
96115 [75432753]
96118 [75432753]
96119 [75432753]
96124 [75432727]
96122 [75432727]
96134 [75432781]
96135 [75432781]
96120 [81535121]
96121 [81535121]
96129 [75432760]
96131 [75432760]
96126 [75432760]
96125 [75432760]
96132 [75432781]
96130 [75432781]
96142 [75432727]
96143 [75432727]
93728 [90071342]
93727 [90071342]
96137 [75432727]
96138 [75432727]
96152 [75432760]
96153 [75432760]
96155 [75432760]
96144 [81392438]
96145 [81392438]
96148 [81392438]
96140 [75432781]
96141 [75432781]
96149 [75432760]
96150 [75432760]
96160 [90071243]
96158 [90071243]
96159 [90071243]
96164 [90071243]
96154 [75432781]
96163 [75432753]
96161 [75432753]
96173 [75432760]
96171 [75432760]
96170 [75432760]
96168 [75432760]
92181 [75432727]
92182 [75432727]
96177 [90071243]
96178 [90071243]
96179 [90071243]
96182 [90071243]
96165 [75432760]
96167 [75432760]
96189 [87313870]
96190 [87313870]
96187 [87313870]
96188 [87313870]
96183 [75432741]
96186 [75432741]
96193 [75432760]
96194 [75432760]
96198 [75432753]
96199 [75432753]
96205 [90071243]
96204 [90071243]
96207 [90071243]
96209 [75432753]
96208 [75432753]
96200 [75432760]
96203 [75432760]
94185 [75432760]
94184 [75432760]
94186 [75432760]
96212 [75432760]
96213 [75432760]
96216 [75432760]
96214 [75432760]
92743 [75432753]
92742 [75432753]
96226 [75432760]
96227 [75432760]
96229 [75432760]
95222 [81524762, 81592842]
95225 [81524762, 81592842]
95224 [81524762, 81592842]
96219 [90071243]
96220 [90071243]
96223 [75432768]
96224 [75432768]
96231 [90071243]
96233 [90071243]
96242 [75432760]
96234 [75432760]
96235 [75432768]
96239 [75432768]
96244 [75432781]
96247 [75432781]
96241 [75432781]
96240 [75432781]
96237 [75432768]
96232 [75432768]
96245 [75432760]
96246 [75432760]
96254 [75432760]
96257 [75432760]
96262 [75432768]
96265 [75432768]
96251 [75432768]
96260 [75432768]
96263 [75432727]
96255 [75432727]
96258 [75432727]
96253 [75432727]
96259 [75432781]
96272 [75432760]
96269 [75432760]
96266 [75432781]
96268 [75432741]
96270 [75432741]
96286 [75432741]
96274 [75432781]
96271 [75432781]
96278 [75432781]
96280 [75432781]
96296 [75432768]
96293 [75432768]
96275 [75432760]
96279 [75432760]
96282 [75432760]
96283 [75432760]
96294 [75432760]
96298 [75432760]
96288 [75432727]
96292 [75432727]
96273 [75432753]
96277 [75432753]
96297 [75432768]
96289 [75432768]
96287 [75432741]
96290 [75432741]
96299 [75432741]
96303 [81592842]
96302 [81592842]
96316 [90071243]
96313 [90071243]
96305 [90071243]
96300 [90071243]
96311 [90071243]
96307 [90071243]
96317 [81524762, 81592842]
96310 [81524762, 81592842]
96308 [75432760]
96309 [75432760]
96312 [75432760]
96323 [75432760]
96319 [75432760]
96322 [75432753]
96328 [75432753]
96326 [75432727]
96324 [75432727]
96318 [75432753]
96320 [75432753]
96331 [81535121]
96337 [81535121]
96333 [90071243]
96335 [90071243]
96340 [75432760]
96329 [75432781]
96336 [75432781]
96351 [81524762, 81592842]
96347 [81524762, 81592842]
96344 [81392438]
96346 [81392438]
96348 [75432781]
96349 [75432781]
96352 [75432781]
96354 [75432781]
96367 [75432727]
96361 [75432727]
96371 [90071243]
96369 [90071243]
96357 [75432727]
96360 [75432727]
96362 [75432760]
87168 [75432727]
96364 [75432760]
87169 [75432727]
87170 [75432727]
97049 [75432741]
97047 [75432741]
96372 [90071243]
96370 [90071243]
96374 [90071243]
96376 [90071243]
97448 [75432781]
97450 [75432781]
96858 [90071342]
96859 [90071342]
96864 [90071342]
96867 [90071342]
96383 [75432741]
96388 [75432727]
96375 [75432741]
96386 [90071243]
96389 [90071243]
96425 [75432753]
96436 [75432753]
96726 [75432753]
96728 [75432753]
96737 [81535121]
96736 [81535121]
96555 [75432727]
96562 [75432727]
96709 [75432760]
96711 [75432760]
96758 [90071243]
96760 [90071243]
96748 [75432753]
96744 [75432753]
96762 [75432768]
96751 [75432753]
96765 [75432768]
96767 [75432768]
96768 [75432768]
96766 [75432741]
96771 [75432741]
96761 []
96763 []
96764 []
96769 [90071243]
96770 [90071243]
96775 [75432760]
96778 [75432760]
96781 [90071342]
96784 [90071342]
96772 [75432760]
93832 [75432768]
93834 [75432768]
93835 [75432768]
96777 [90071243]
96780 [90071243]
96782 [90071342]
96779 [90071342]
96796 [75432760]
96802 [75432760]
96800 [75432760]
96786 [81524762, 81592842]
96790 [81524762, 81592842]
96774 [81535121]
96776 [81535121]
96783 [90071342]
96785 [90071342]
96787 [90071342]
97024 [75432710]
97023 [75432710]
96792 [75432727]
96794 [75432727]
96793 [75432727]
96795 [75432727]
96797 [75432739]
96798 [75432727]
96799 [75432753]
96801 [75432768]
96803 [75432768]
96810 [75432753]
96812 [75432753]
96804 [75432768]
96805 [75432768]
93235 [75432768]
93237 [75432768]
93238 [75432768]
93612 [75432768]
96806 [75432760]
96808 [75432760]
96807 [75432753]
96809 [75432753]
96811 [81535121]
96813 [75432741]
96814 [75432741]
96816 [75432741]
96815 [81535121]
96819 [81535121]
96818 [75432760]
96820 [75432760]
96821 [75432781]
96822 [87313870]
96824 [87313870]
96826 [87313870]
96830 [87313870]
96825 [75432768]
96827 [75432768]
90281 [75432768]
96823 [75432741]
96828 [81524762, 81592842]
96829 [81524762, 81592842]
96832 [75432753]
96831 [75432753]
92844 [75432768]
96833 [75432727]
96837 [75432727]
96838 [75432768]
96836 [75432768]
96834 [75432741]
96835 [75432741]
96841 [75432760]
96840 [75432760]
96843 [90071342]
96846 [90071342]
96844 [90071342]
96849 [75432753]
96853 [75432753]
96860 [75432753]
96842 [81392438]
96845 [75432768]
96847 [75432768]
93667 [75432768]
93665 [75432768]
96848 [75432768]
96851 [75432768]
96850 [75432760]
96854 [75432760]
96856 [75432753]
96857 [75432753]
96852 [75432753]
96855 [75432753]
96866 [75432741]
96868 [75432741]
96862 [75432741]
96861 [75432768]
96863 [75432768]
97043 [75432753]
97044 [75432753]
96865 [75432753]
96870 [75432768]
96882 [75432768]
96877 [90071243]
96875 [90071342]
96881 [90071243]
96872 [90071243]
96876 [90071243]
96880 [90071243]
96869 [75432781]
96871 [75432781]
96893 [90071243]
96891 [90071243]
96889 [90071243]
96896 [90071243]
96884 [75432753]
96886 [75432753]
96879 [81535121]
96883 [81535121]
96902 [75432768]
96898 [75432768]
96878 [75432741]
96888 [75432741]
96887 [75432753]
96909 [75432741]
96912 [75432741]
96905 [75432760]
96894 [75432768]
96897 [75432768]
96908 [75432760]
96901 [75432760]
96906 [75432760]
96907 [75432760]
96899 [75432727]
96892 [75432760]
96900 [75432760]
96911 [75432781]
96916 [75432781]
96910 [75432781]
96904 [81524762, 81592842]
96914 [75432781]
96903 [81524762, 81592842]
93354 [90071342]
93355 [90071342]
93356 [90071342]
93359 [90071342]
93357 [90071342]
93358 [90071342]
96913 [75432753]
96918 [75432753]
96922 [75432760]
96927 [75432760]
96928 [81524762, 81592842]
96917 [75432753]
96926 [81524762, 81592842]
96920 [75432753]
96931 [75432760]
96932 [75432760]
96924 [81392438]
96925 [81392438]
96919 [90071243]
96937 [75432760]
96939 [75432760]
96929 [75432753]
96921 [75432768]
96923 [75432768]
96938 [75432760]
96935 [75432760]
96933 [75432753]
96936 [75432753]
96941 [75432753]
96944 [75432753]
96945 [75432753]
96946 [75432753]
96940 [75432753]
96943 [75432753]
96942 [75432753]
96947 [75432727]
96952 [75432760]
96953 [75432760]
96954 [75432760]
96951 [81524762, 81592842]
96950 [81524762, 81592842]
96963 [75432727]
96962 [75432727]
96959 [81535121]
96960 [81535121]
96955 [75432741]
96956 [75432741]
96958 [81535121]
96966 [81535121]
96967 [81535121]
96964 [81535121]
96965 [81535121]
96968 [75432760]
96969 [75432760]
96961 [90071243]
96973 [81524762, 81592842]
96972 [81524762, 81592842]
96970 [75432768]
96971 [75432768]
96981 [75432753]
96980 [75432753]
96975 [87313870]
96976 [87313870]
96977 [87313870]
96979 [87313870]
96989 [75432760]
96990 [75432760]
96994 [75432781]
96995 [75432781]
93669 [75432768]
96984 [75432727]
96974 [75432753]
96985 [75432768]
96986 [75432768]
96987 [75432753]
96988 [75432753]
96982 [75432727]
96983 [75432727]
96996 [75432768]
96997 [75432768]
96991 [75432781]
96992 [75432781]
96998 [81535121]
96999 [81535121]
93587 [75432768]
93588 [75432768]
93586 [75432768]
97001 [81524762, 81592842]
93668 [75432768]
97000 [75432753]
97003 [90071243]
97006 [75432727]
97008 [75432727]
97004 [75432753]
97005 [75432753]
97007 [75432753]
97017 [75432727]
93272 [75432768]
97010 [75432741]
97012 [75432741]
97013 [75432741]
97015 [75432741]
97014 [81535121]
97016 [81535121]
97021 [75432768]
97022 [75432768]
97011 [75432760]
93226 [75432768]
93224 [75432768]
93604 [75432768]
97018 [87313870]
97026 [75432741]
97025 [75432741]
97028 [75432741]
97019 [75432781]
97020 [75432781]
97027 [75432753]
97031 [90071243]
97030 [90071243]
97029 [75432768]
97046 [90071243]
97048 [90071243]
97039 [81524762, 81592842]
97040 [81524762, 81592842]
97032 [75432760]
97033 [75432760]
97034 [75432760]
97035 [75432760]
97037 [75432760]
97036 [75432727]
97038 [75432727]
97051 [75432781]
97052 [75432781]
97050 [75432727]
97042 [75432768]
97041 [75432768]
97060 [75432760]
97059 [75432760]
97053 [75432753]
97054 [75432753]
97063 [81535121]
97065 [81535121]
97061 [75432760]
97062 [75432760]
97064 [75432760]
97055 [90071243]
97056 [90071243]
97068 [75432753]
97066 [75432753]
97057 [81524762, 81592842]
97058 [81524762, 81592842]
97067 [75432753]
97069 [75432753]
97070 [75432727]
97071 [75432727]
97073 [81592842]
97074 [81592842]
97084 [75432753]
97080 [75432753]
97089 [75432741]
97087 [75432741]
97077 [75432753]
97078 [75432753]
97079 [75432753]
97082 [75432753]

In [23]:
formatted_dicts[0]

{'elv_id': '95260',
 'client_id': '86877zmcc',
 'elv_plan_code': 'RMRECRDCA0101202612312026',
 'normalized_account_type': 'DCA',
 'plan_status': 'ACTIVE',
 'organization_id': 8441,
 'rmrcode': 'RMRECR',
 'date_plan_start': 1767225600000,
 'date_plan_end': 1798675200000,
 'card': True,
 'plan_primary_config.max_election_amount_type.max_election_amount_type': 'IRS_LIMIT',
 'annual_election_max': 7500.0,
 'annual_election_min': 0.0,
 'run_out': 90,
 'run_out_termed_ee_matches_plan': True,
 'rollover': False,
 'name': 'RMRECR DCA 2026',
 'account_manager': [90071342],
 'auto_post_contributions': False,
 'annual_election_auto_adjust': True,
 'list_id': 901102729288,
 'client_opportunity': '86877zmcc',
 'client_contact': '86877zmcc',
 'client_brokerage': ['86877zmcc'],
 'client_client': '86877zmcc',
 'client_fsa': ['86877zmcc'],
 'client_dca': ['86877zmcc'],
 'client_hsa': ['86877zmcc'],
 'client_hra': ['86877zmcc'],
 'client_pkg': ['86877zmcc'],
 'client_trn': ['86877zmcc'],
 'client_lsa': ['86877zmcc'],
 'client_ado': ['86877zmcc'],
 'client_edu': ['86877zmcc'],
 'client_cobra': ['86877zmcc'],
 'client_data card': '86877zmcc',
 'client_data file': '86877zmcc',
 'client_fund': ['86877zmcc'],
 'client_inv': ['86877zmcc'],
 'client_clm': '86877zmcc'}

In [ ]:
create_responses = {}


for plan_dict in formatted_dicts:
    try:
        model = MODEL_LOOKUP.get(plan_dict.get("list_id"))

        narrow_dict = { k:v for k,v in plan_dict.items() if k in dir(model) and pd.notna(v) }

        narrow_dict['list_id'] = int(narrow_dict["list_id"])

        plan_model = model(**narrow_dict)

        create_res = rcu.create(plan_model)

        create_responses[plan_dict.get("elv_id")] = create_res
    except Exception as e:
        print(f"error creating plan card for {plan_dict.get("elv_id")}")

In [ ]:
with open("create_responses.json", "w") as f:
    json.dump(create_responses, f, indent=4)

In [ ]:
formatted_dicts[0]

In [ ]:
for plan_dict in plan_dicts:
    model = MODEL_LOOKUP.get(plan_dict.get("list_id"))
    print(model)

    narrow_dict = { k:v for k,v in plan_dict.items() if k in dir(model) and pd.notna(v) }
    display(narrow_dict)

    plan_model = model(**narrow_dict)

    # for key, value in narrow_dict.items():
    #     print(f"\n{key}:\n\t{value} ({type(value)})\n\t{field_map.get(key).type if key in field_map else ".."}")


    create_res = rcu.create(plan_model)

    break

In [24]:
create_responses = []
with open("create_responses.json", "r") as f:
    create_responses = json.load(f)

In [34]:
missing_responses = {k: v for k, v in create_responses.items() if pd.isna(v) or not v.get("id")}

In [35]:
missing_responses

{'95793': None,
 '95808': None,
 '95807': None,
 '95804': None,
 '96863': None,
 '97043': None,
 '97154': None,
 '97157': None,
 '97158': None,
 '98996': None,
 '98997': None,
 '94431': None}

In [44]:
plans_to_retry = [ask_dict for ask_dict in formatted_dicts if ask_dict['elv_id'] not in create_responses or ask_dict['elv_id'] in missing_responses]

In [46]:
len(plans_to_retry)

83

In [83]:
deactivated_users = [81524762, 81524777, 75432710]

In [87]:
retry_create_responses = {}

for plan_dict in plans_to_retry:
    try:
        model = MODEL_LOOKUP.get(plan_dict.get("list_id"))
        # display(plan_dict)

        narrow_dict = { k:v for k,v in plan_dict.items() if k in dir(model) and ((not isinstance(v, list) and pd.notna(v)) or (isinstance(v, list) and len(v) > 0)) }
        # display(narrow_dict)

        narrow_dict['account_manager'] = [c for c in narrow_dict['account_manager'] if c not in deactivated_users]

        narrow_dict['list_id'] = int(narrow_dict["list_id"])

        plan_model = model(**narrow_dict)

        create_res = rcu.create(plan_model)

        create_responses[plan_dict.get("elv_id")] = create_res
        
    except Exception as e:
        print(f"error creating plan card for {plan_dict.get("elv_id")}:\n{e}")

error creating plan card for 95808:
'account_manager'
error creating plan card for 93359:
'account_manager'
error creating plan card for 97153:
'account_manager'
error creating plan card for 97154:
'account_manager'
Error patching task (868g9m612): All users must have access to task
Error patching task (868g9m636): All users must have access to task
error creating plan card for 97306:
'account_manager'

In [88]:
final_error_ids = [95808, 93359, 97153, 97154, 97306]

In [ ]:
# rows_to_retry = narrow_df[narrow_df['elv_id'].isin([int(r.get("elv_id")) for r in plans_to_retry])]

In [67]:
rows_to_retry['client_dca']

382     86877zjdx
391     86877zjdx
734     86877zwd4
735     86877zwd4
1146    86877zmzn
          ...
6398    868adw48d
6855    868dzycxh
6856    868dzycxh
6857    868dzycxh
6860    868dzycxh
Name: client_dca, Length: 83, dtype: object

In [90]:
more_rows_to_retry = narrow_df[narrow_df['elv_id'].isin(final_error_ids)]
more_rows_to_retry

,elv_id,client_id,elv_plan_code,normalized_account_type,plan_status,organization_id,rmrcode,date_plan_start,date_plan_end,card,...,client_trn,client_lsa,client_ado,client_edu,client_cobra,client_data card,client_data file,client_fund,client_inv,client_clm
1979,95808,86877zuwt,RMRSTAFSA0101202612312026,FSA,ACTIVE,8760,RMRSTA,2026-01-01,2026-12-31,True,...,86877zuwt,86877zuwt,86877zuwt,86877zuwt,86877zuwt,86877zuwt,86877zuwt,86877zuwt,86877zuwt,86877zuwt
4707,93359,86877zj8d,RMRARPADO0101202612312026,ADOPTION,ACTIVE,10040,RMRARP,2026-01-01,2026-12-31,False,...,86877zj8d,86877zj8d,86877zj8d,86877zj8d,86877zj8d,86877zj8d,86877zj8d,86877zj8d,86877zj8d,86877zj8d
5667,97153,86877zj72,RMRACANFSA0101202612312026,FSA,ACTIVE,10277,RMRACAN,2026-01-01,2026-12-31,True,...,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72
5672,97154,86877zj72,RMRACANDCA0101202612312026,DCA,ACTIVE,10277,RMRACAN,2026-01-01,2026-12-31,True,...,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72
6198,97306,868b91d1v,RMROMSWEL0101202612312026,SPECIALTY,ACTIVE,12392,RMROMS,2026-01-01,2026-12-31,False,...,868b91d1v,868b91d1v,868b91d1v,868b91d1v,868b91d1v,868b91d1v,868b91d1v,868b91d1v,868b91d1v,868b91d1v

In [92]:
more_rows_to_retry

,elv_id,client_id,elv_plan_code,normalized_account_type,plan_status,organization_id,rmrcode,date_plan_start,date_plan_end,card,...,client_trn,client_lsa,client_ado,client_edu,client_cobra,client_data card,client_data file,client_fund,client_inv,client_clm
1979,95808,86877zuwt,RMRSTAFSA0101202612312026,FSA,ACTIVE,8760,RMRSTA,2026-01-01,2026-12-31,True,...,86877zuwt,86877zuwt,86877zuwt,86877zuwt,86877zuwt,86877zuwt,86877zuwt,86877zuwt,86877zuwt,86877zuwt
4707,93359,86877zj8d,RMRARPADO0101202612312026,ADOPTION,ACTIVE,10040,RMRARP,2026-01-01,2026-12-31,False,...,86877zj8d,86877zj8d,86877zj8d,86877zj8d,86877zj8d,86877zj8d,86877zj8d,86877zj8d,86877zj8d,86877zj8d
5667,97153,86877zj72,RMRACANFSA0101202612312026,FSA,ACTIVE,10277,RMRACAN,2026-01-01,2026-12-31,True,...,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72
5672,97154,86877zj72,RMRACANDCA0101202612312026,DCA,ACTIVE,10277,RMRACAN,2026-01-01,2026-12-31,True,...,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72,86877zj72
6198,97306,868b91d1v,RMROMSWEL0101202612312026,SPECIALTY,ACTIVE,12392,RMROMS,2026-01-01,2026-12-31,False,...,868b91d1v,868b91d1v,868b91d1v,868b91d1v,868b91d1v,868b91d1v,868b91d1v,868b91d1v,868b91d1v,868b91d1v

In [108]:

final_formatted_dicts = [
    format_dict(r.to_dict()) for _, r in more_rows_to_retry.iterrows()
]

95808 []
93359 [90071342]
97153 []
97154 []
97306 [75432781]

In [99]:
retry_create_responses = {}

for plan_dict in final_formatted_dicts:
    try:
        model = MODEL_LOOKUP.get(plan_dict.get("list_id"))
        display(plan_dict)
        

        narrow_dict = { k:v for k,v in plan_dict.items() if k in dir(model) and ((not isinstance(v, list) and pd.notna(v)) or (isinstance(v, list) and len(v) > 0)) }
        # display(narrow_dict)

        narrow_dict['account_manager'] = [c for c in narrow_dict['account_manager'] if c not in deactivated_users]

        narrow_dict['list_id'] = int(narrow_dict["list_id"])

        plan_model = model(**narrow_dict)

        create_res = rcu.create(plan_model)

        create_responses[plan_dict.get("elv_id")] = create_res
        
    except Exception as e:
        print(f"error creating plan card for {plan_dict.get("elv_id")}:\n{e}")

    break

{'elv_id': '95808',
 'client_id': '86877zuwt',
 'elv_plan_code': 'RMRSTAFSA0101202612312026',
 'normalized_account_type': 'FSA',
 'plan_status': 'ACTIVE',
 'organization_id': 8760,
 'rmrcode': 'RMRSTA',
 'date_plan_start': 1767225600000,
 'date_plan_end': 1798675200000,
 'card': True,
 'plan_primary_config.max_election_amount_type.max_election_amount_type': 'IRS_LIMIT',
 'annual_election_max': 6800.0,
 'annual_election_min': 0.0,
 'run_out': 90,
 'run_out_termed_ee_matches_plan': True,
 'rollover': True,
 'rollover_max': 680.0,
 'name': 'RMRSTA FSA 2026',
 'lpf': True,
 'date_admin_start': 1577836800000,
 'auto_post_contributions': False,
 'annual_election_auto_adjust': True,
 'list_id': 901102729124,
 'client_opportunity': '86877zuwt',
 'client_contact': '86877zuwt',
 'client_brokerage': ['86877zuwt'],
 'client_client': '86877zuwt',
 'client_fsa': ['86877zuwt'],
 'client_dca': ['86877zuwt'],
 'client_hsa': ['86877zuwt'],
 'client_hra': ['86877zuwt'],
 'client_pkg': ['86877zuwt'],
 'client_trn': ['86877zuwt'],
 'client_lsa': ['86877zuwt'],
 'client_ado': ['86877zuwt'],
 'client_edu': ['86877zuwt'],
 'client_cobra': ['86877zuwt'],
 'client_data card': '86877zuwt',
 'client_data file': '86877zuwt',
 'client_fund': ['86877zuwt'],
 'client_inv': ['86877zuwt'],
 'client_clm': '86877zuwt'}

error creating plan card for 95808:
'account_manager'