In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd

In [5]:
clients = pd.read_pickle(r"C:\Users\james.richmond\Desktop\repos\mynotebook\cache\250929_ALL_CLIENTS_CLICKUP.pkl")

In [9]:
int_task_ids = clients[clients['client_id'].apply(lambda x: x.isnumeric())]

In [10]:
int_task_ids

,client_id,client_name,cu_client_description,cu_client_archived,cu_client_assignees,cu_client_assignees,cu_client_tags,cu_client_url,cu_client_status,status.id,...,ducks,data_transmission_details,divisional_invoicing,temp_am_cobra,temp_account_manager,data_start,temp_flex_divisions,temp_cobra_divisions,data_end,year_oe_approved
872,868781798,Tegelerinsurance,,False,[],[],[],https://app.clickup.com/t/868781798,terminated,sc901102596133_sEOysHhM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
873,868781797,"TechnoAlpin USA, Inc.",,False,[],[],[],https://app.clickup.com/t/868781797,terminated,sc901102596133_sEOysHhM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
874,868781795,"TechInsights USA, Inc",,False,[],[],[],https://app.clickup.com/t/868781795,terminated,sc901102596133_sEOysHhM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
875,868781793,Taylor Anderson LLP,,False,[],[],[],https://app.clickup.com/t/868781793,terminated,sc901102596133_sEOysHhM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
876,868781791,TARC,,False,[],[],[],https://app.clickup.com/t/868781791,terminated,sc901102596133_sEOysHhM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027,868781707,Leeds Equity,,False,[],[],[],https://app.clickup.com/t/868781707,terminated,sc901102596133_sEOysHhM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1028,868781703,Latitude 36 Foods LLC,,False,[],[],[],https://app.clickup.com/t/868781703,terminated,sc901102596133_sEOysHhM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1029,868781702,Laird Norton Wealth Management,,False,[],[],[],https://app.clickup.com/t/868781702,terminated,sc901102596133_sEOysHhM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1030,868781700,La Jolla Music Society,,False,[],[],[],https://app.clickup.com/t/868781700,terminated,sc901102596133_sEOysHhM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1260,868781613,Visiting Nurse Association,,False,[],[],[],https://app.clickup.com/t/868781613,terminated,sc901102596133_sEOysHhM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
display(clients[clients['client_name'].apply(lambda x: "client_id" in x.lower())])

Empty DataFrame
Columns: [client_id, client_name, cu_client_description, cu_client_archived, cu_client_assignees, cu_client_assignees, cu_client_tags, cu_client_url, cu_client_status, status.id, status.color, status.type, status.orderindex, creator.id, creator.username, creator.color, creator.email, creator.profilePicture, list.id, list.name, list.access, time_spent, tier, cu_client_date_admin_start, previous_names, wave, phone_direct, phone_direct_ext, phone_fax, website, email_domains, address_street, address_street_line_, address_city, address_state, address_zip, address_billing, address_mail, social_twitter, social_linkedin, social_facebook, phone_mobile, eligible_employee_count, termination_details, previous_administrator, broker_involvement, client_contacts, client_project, client_fsa, client_hsa, client_dca, client_hra, client_lsa, client_pkg, client_cobra, client_data, client_brokerage, opportunity_client, client_ado, client_edu, client_inv, client_fund, client_elv, name_umbrella, initial_deposit, date_rate_expiration, divisions, cu_client_elv_id, hq_city, hq_state, address, update_account_managers, client_trn, rmrcode, cu_client_account_manager, cobra_manager, name_operational, elevate_auto_renew, ducks, data_transmission_details, divisional_invoicing, temp_am_cobra, temp_account_manager, data_start, temp_flex_divisions, temp_cobra_divisions, data_end, year_oe_approved]
Index: []

[0 rows x 88 columns]